# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a993c7bdf21eb1b4cff0eab645cfcd24f67ff3a6571a45b2e09bdd81ffcd062138583516d24b1aa0e24cd192672f84098b5778b539094c6a045a66e14b5d4428

test:
  secret_key_base: db71cf671106f2f9e80a656db2fab49dc71a8fc5ce6bcb2f0ef98cc562bc24e852e52a38e0af04e60ee0f261a16d859b1198f4440634c0a8d20710661cd0826c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
